export const charityFormControls = [
  {
    name: "name",
    label: "Name",
    placeholder: "Your charity name",
    componentType: "input",
    type: "text",
    required: true,
  },
  {
    name: "location",
    label: "Location",
    placeholder: "Your charity location",
    componentType: "input",
    type: "text",
    required: true,
  },
  {
    name: "organizationType",
    label: "Organization Type",
    placeholder: "Your organization type",
    componentType: "select",
    type: "select",
    options: ["Charity", "Second Hand Market", "Recycler"],
    required: true,
  },
  {
    name: "capacity",
    label: "Capacity",
    placeholder: "Your charity capacity",
    componentType: "select",
    type: "select",
    options: ["low", "medium", "high"],
    required: true,
  },
  {
    name: "accepts",
    label: "Accepts",
    placeholder: "e.g. Food, Clothing, Electronics",
    componentType: "input",
    type: "text",
    required: true,
  },
  {
    name: "email",
    label: "Email",
    type: "email",
    required: true,
    disabled: true,
    componentType: "input",
  },
  {
    name: "phoneNumber",
    label: "Phone Number",
    type: "tel",
    required: true,
    disabled: true,
    componentType: "input",
  },
];

export const initialCharityFormData = {
  name: "",
  location: "",
  organizationType: "",
  capacity: "",
  accepts: "",
  email: "",
  phoneNumber: "",
};

export const partnerFormControls = [
  {
    name: "name",
    label: "Retailer/Business Name",
    placeholder: "Your business name",
    componentType: "input",
    type: "text",
    required: true,
  },
  {
    name: "itemName",
    label: "Item Name",
    placeholder: "e.g. Old Clothes, Bananas",
    componentType: "input",
    type: "text",
    required: true,
  },
  {
    name: "quantity",
    label: "Quantity",
    placeholder: "e.g. 10 items, 5 kg",
    componentType: "input",
    type: "number",
    required: true,
  },
  {
    name: "category",
    label: "Category",
    placeholder: "e.g. Clothing, Electronics, Furniture",
    componentType: "select",
    type: "select",
    options: [
      "Clothing",
      "Electronics",
      "Furniture",
      "Food",
      "Books",
      "Household Items",
      "Other",
    ],
    required: true,
  },
  {
    name: "location",
    label: "Location",
    placeholder: "Store Location",
    componentType: "input",
    type: "text",
    required: true,
  },
  {
    name: "price",
    label: "Price (if applicable in rupees)",
    placeholder: "e.g. $10, Free, Donation-based",
    componentType: "input",
    type: "number",
  },
  {
    name: "description",
    label: "Description (optional)",
    placeholder: "Additional details about the items",
    componentType: "textarea", // Use textarea for longer descriptions
  },
   {
    name: "email",
    label: "Email",
    type: "email",
    required: true,
    disabled: true,
    componentType: "input",
  },
  {
    name: "phoneNumber",
    label: "Phone Number",
    type: "tel",
    required: true,
    disabled: true,
    componentType: "input",
  },
];

export const initialPartnerFormData = {
  name: "",
  itemName: "",
  quantity: 0,
  category: "",
  location: "",
  price: 0,
  description: "",
  email: "", 
  phoneNumber: "",
};
